## Data cleaning

In [1]:
#importing the libraries
import os
import numpy as np
import pandas as pd
import scipy.stats as stats
from sklearn.linear_model import LinearRegression
import matplotlib.pyplot as plt
import seaborn as sns

#magic commands
%matplotlib inline 
%config InlineBackend.figure_format = 'retina'

In [2]:
headers = [
    'Symboling', 'Normalized-losses', 'Producer',
    'Fuel-type', 'Aspiration', 'Num-of-doors', 
    'Body-style', 'Drive-wheels', 'Engine-location',
    'Wheel-base', 'Length', 'Width',
    'Height', 'Curb-weight', 'Engine-type',
    'Num-of-cylinders', 'Engine-size', 'Fuel-system', 
    'Bore', 'Stroke', 'Compression-ratio', 
    'Horsepower', 'Peak-rpm', 'City-mpg', 
    'Highway-mpg', 'Price',
]

data = pd.read_csv('car_data.csv', names=headers)

In [3]:
data.head()

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
0,auto,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,145,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21.0,27.0,13495
2,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21.0,27.0,16500
3,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154,5000,19.0,26.0,16500
4,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102,5500,24.0,30.0,13950

In [4]:
data.tail()

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141.0,mpfi,3.78,3.15,9.5,114,5400,23.0,28.0,16845
202,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141.0,mpfi,3.78,3.15,8.7,160,5300,19.0,25.0,19045
203,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173.0,mpfi,3.58,2.87,8.8,134,5500,18.0,23.0,21485
204,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145.0,idi,3.01,3.40,23.0,106,4800,26.0,27.0,22470
205,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141.0,mpfi,3.78,3.15,9.5,114,5400,19.0,25.0,22625

In [5]:
# Replace '?' with 'NaN'
data.replace('?', np.NaN, inplace=True)

In [6]:
data.shape

(206, 26)

In [7]:
data.dtypes

Symboling             object
Normalized-losses     object
Producer              object
Fuel-type             object
Aspiration            object
Num-of-doors          object
Body-style            object
Drive-wheels          object
Engine-location       object
Wheel-base           float64
Length               float64
Width                float64
Height               float64
Curb-weight          float64
Engine-type           object
Num-of-cylinders      object
Engine-size          float64
Fuel-system           object
Bore                  object
Stroke                object
Compression-ratio    float64
Horsepower            object
Peak-rpm              object
City-mpg             float64
Highway-mpg          float64
Price                 object
dtype: object

In [8]:
# Change data types
data[['Normalized-losses','Bore', 'Stroke', 'Horsepower', 'Peak-rpm', 'Price']] = \
data[['Normalized-losses','Bore', 'Stroke', 'Horsepower', 'Peak-rpm', 'Price']].astype('float64')

In [9]:
# Drop rows where there are at least 15 not np.nan values
data.dropna(thresh=15, inplace=True)

In [10]:
data.head()

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
1,3,145.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
2,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
3,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
4,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
5,2,164.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 205 entries, 1 to 205
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Symboling          205 non-null    object
 1   Normalized-losses  168 non-null    float64
 2   Producer           205 non-null    object
 3   Fuel-type          205 non-null    object
 4   Aspiration         205 non-null    object
 5   Num-of-doors       203 non-null    object
 6   Body-style         205 non-null    object
 7   Drive-wheels       205 non-null    object
 8   Engine-location    205 non-null    object
 9   Wheel-base         205 non-null    float64
 10  Length             205 non-null    float64
 11  Width              205 non-null    float64
 12  Height             205 non-null    float64
 13  Curb-weight        205 non-null    float64
 14  Engine-type        205 non-null    object
 15  Num-of-cylinders   205 non-null    object
 16  Engine-size        205 non-null    float64
 17  Fuel-system        205 non-null    object
 18  Bore               201 non-null    float64
 19  Stroke             201 non-null    float64
 20  Compression-ratio  205 non-null    float64
 21  Horsepower         203 non-null    float64
 22  Peak-rpm           203 non-null    float64
 23  City-mpg           205 non-null    float64
 24  Highway-mpg        205 non-null    float64
 25  Price              201 non-null    float64
dtypes: float64(15), object(11)
memory usage: 43.2+ KB

In [12]:
# Total number of missing values
num_rows = data.shape[0]
miss_val = num_rows - data.count()

print(f'There are {data.shape[0]} rows and {data.shape[1]} columns in the dataset')
print('    ')
print(data.isnull().sum())
print('    ')
print('Total number of missing values are:', miss_val.sum())

There are 205 rows and 26 columns in the dataset

Symboling             0
Normalized-losses    37
Producer              0
Fuel-type             0
Aspiration            0
Num-of-doors          2
Body-style            0
Drive-wheels          0
Engine-location       0
Wheel-base            0
Length                0
Width                 0
Height                0
Curb-weight           0
Engine-type           0
Num-of-cylinders      0
Engine-size           0
Fuel-system           0
Bore                  4
Stroke                4
Compression-ratio     0
Horsepower            2
Peak-rpm              2
City-mpg              0
Highway-mpg           0
Price                 4
dtype: int64

Total number of missing values are: 55

Since almost 20% of the missing data is present in the 'Losses-normalized' column, deleting them could invalidate the result of the analysis, so I decide to replace them with the average conditioned by the manufacturer.

In [13]:
conditioned_mean_ = dict(data['Normalized-losses'].groupby(data['Producer']).mean())
conditioned_mean_

{'alfa-romero': 145.0,
 'audi': 161.0,
 'bmw': 190.0,
 'chevrolet': 100.0,
 'dodge': 133.44444444444446,
 'honda': 103.0,
 'isuzu': 167.0,
 'jaguar': 145.0,
 'mazda': 123.93333333333334,
 'mercedes-benz': 102.8,
 'mercury': 156.0,
 'mitsubishi': 146.2,
 'nissan': 135.16666666666666,
 'peugot': 161.0,
 'plymouth': 129.0,
 'porsche': 186.0,
 'renault': 165.0,
 'saab': 127.0,
 'subaru': 92.25,
 'toyota': 110.29032258064517,
 'volkswagen': 121.25,
 'volvo': 91.45454545454545}

With the aim of exercising my knowledge of functions, I also achieve this by defining a function

In [14]:
#def conditioned_mean(cond_col, num_col, producer):
#    '''Takes two Series of a DataFrame,
#    and determine the mean of those values
#    where the if statement is satisfied
#     '''

#    basket = []

#    for x, y in zip(cond_col,num_col):
#        if x == producer:
#            basket.append(y) 

#    z = pd.DataFrame(basket)
#    return float(round(z.mean(), 2))

In [15]:
# Find all kinds and averages for machine manufacturers
#producer_list = list(data['Producer'].unique())
#means = []
#for producer in producer_list:
#    means.append(conditioned_mean(data['Producer'], data['Normalized-losses'], producer))
#conditioned_mean_= dict(zip(producer_list, means))
#print(conditioned_mean_)

In [16]:
# Fill the missing values with the corresponding mean
def fill_means(condition_col_name, numeric_col_name, means, dataframe):
    condition_col = dataframe[condition_col_name]
    numeric_col = dataframe[numeric_col_name]
    new_numeric_col = []
    
    for x, y in zip(condition_col, numeric_col):
        if str(y).lower() == 'nan':  # Convert to string because 'np.nan' is a special floating-point value
            y = means[x]
        new_numeric_col.append(y) 
    new_numeric_col = pd.Series(new_numeric_col)
    dataframe['Normalized-losses'] = new_numeric_col
    
    return dataframe.head()

In [17]:
fill_means('Producer','Normalized-losses', conditioned_mean_, data)

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,City-mpg,Highway-mpg,Price
1,3,145.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,13495.0
2,3,145.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,21.0,27.0,16500.0
3,1,164.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,19.0,26.0,16500.0
4,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,24.0,30.0,13950.0
5,2,161.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,18.0,22.0,17450.0

In [18]:
data.dropna(inplace = True)

In [19]:
data.isnull().sum()

Symboling            0
Normalized-losses    0
Producer             0
Fuel-type            0
Aspiration           0
Num-of-doors         0
Body-style           0
Drive-wheels         0
Engine-location      0
Wheel-base           0
Length               0
Width                0
Height               0
Curb-weight          0
Engine-type          0
Num-of-cylinders     0
Engine-size          0
Fuel-system          0
Bore                 0
Stroke               0
Compression-ratio    0
Horsepower           0
Peak-rpm             0
City-mpg             0
Highway-mpg          0
Price                0
dtype: int64

In [20]:
data.shape

(192, 26)

In [21]:
# Data standardisation
data['City-L/100km'] = round(235 / data["City-mpg"], 2)
data['Highway-L/100km'] = round(235 / data["Highway-mpg"], 2)

In [22]:
data['Height'] = round(data['Height'] / data['Height'].max(), 2)
data['Length'] = round(data['Length'] / data['Length'].max(), 2)
data['Width'] = round(data['Width'] / data['Width'].max(), 2)

In [23]:
data.drop(columns=['City-mpg', 'Highway-mpg'], inplace=True)

In [24]:
data.head()

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,Price,City-L/100km,Highway-L/100km
1,3,145.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,13495.0,11.19,8.70
2,3,145.0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111.0,5000.0,16500.0,11.19,8.70
3,1,164.0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154.0,5000.0,16500.0,12.37,9.04
4,2,164.0,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102.0,5500.0,13950.0,9.79,7.83
5,2,161.0,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115.0,5500.0,17450.0,13.06,10.68

In [25]:
# Take the columns which are of type 'object' and find the unique values
obj_col = data.dtypes
obj_col = obj_col[obj_col == 'object'].index
obj_col

Index(['Symboling', 'Producer', 'Fuel-type', 'Aspiration', 'Num-of-doors',
       'Body-style', 'Drive-wheels', 'Engine-location', 'Engine-type',
       'Num-of-cylinders', 'Fuel-system'],
      dtype='object')

In [26]:
def unique_items(data):
    for column in obj_col:
        print('  ')
        print(column)
        print(data[column].value_counts())

In [27]:
unique_items(data)

Symboling
0     63
1     51
2     31
3     23
-1    21
-2     3
Name: Symboling, dtype: int64

Producer
toyota           32
nissan           18
honda            13
mitsubishi       13
volkswagen       12
subaru           12
mazda            12
peugot           11
volvo            10
bmw               8
dodge             8
mercedes-benz     8
plymouth          7
saab              6
audi              6
porsche           4
alfa-romero       3
jaguar            3
chevrolet         3
isuzu             2
mercury           1
Name: Producer, dtype: int64

Fuel-type
gas       173
diesel     19
Name: Fuel-type, dtype: int64

Aspiration
std      158
turbo     34
Name: Aspiration, dtype: int64

Num-of-doors
four    111
two      81
Name: Num-of-doors, dtype: int64

Body-style
sedan          91
hatchback      63
wagon          24
hardtop         8
convertible     6
Name: Body-style, dtype: int64

Drive-wheels
fwd    114
rwd     70
4wd      8
Name: Drive-wheels, dtype: int64

Engine-location
front    189
rear       3
Name: Engine-location, dtype: int64

Engine-type
ohc     140
ohcf     15
ohcv     13
dohc     12
l        12
Name: Engine-type, dtype: int64

Num-of-cylinders
four      152
six        24
five       10
eight       4
three       1
twelve      1
Name: Num-of-cylinders, dtype: int64

Fuel-system
mpfi    87
2bbl    64
idi     19
1bbl    11
spdi     9
mfi      1
spfi     1
Name: Fuel-system, dtype: int64

In [28]:
# Correct the syntax of the columns
for i in obj_col:
    data[i] = data[i].str.title()
data

,Symboling,Normalized-losses,Producer,Fuel-type,Aspiration,Num-of-doors,Body-style,Drive-wheels,Engine-location,Wheel-base,...,Engine-size,Fuel-system,Bore,Stroke,Compression-ratio,Horsepower,Peak-rpm,Price,City-L/100km,Highway-L/100km
1,3,145.0,Alfa-Romero,Gas,Std,Two,Convertible,Rwd,Front,88.6,...,130.0,Mpfi,3.47,2.68,9.0,111.0,5000.0,13495.0,11.19,8.70
2,3,145.0,Alfa-Romero,Gas,Std,Two,Convertible,Rwd,Front,88.6,...,130.0,Mpfi,3.47,2.68,9.0,111.0,5000.0,16500.0,11.19,8.70
3,1,164.0,Alfa-Romero,Gas,Std,Two,Hatchback,Rwd,Front,94.5,...,152.0,Mpfi,2.68,3.47,9.0,154.0,5000.0,16500.0,12.37,9.04
4,2,164.0,Audi,Gas,Std,Four,Sedan,Fwd,Front,99.8,...,109.0,Mpfi,3.19,3.40,10.0,102.0,5500.0,13950.0,9.79,7.83
5,2,161.0,Audi,Gas,Std,Four,Sedan,4Wd,Front,99.4,...,136.0,Mpfi,3.19,3.40,8.0,115.0,5500.0,17450.0,13.06,10.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95.0,Volvo,Gas,Turbo,Four,Wagon,Rwd,Front,104.3,...,130.0,Mpfi,3.62,3.15,7.5,162.0,5100.0,18950.0,13.82,10.68
201,-1,95.0,Volvo,Gas,Std,Four,Sedan,Rwd,Front,109.1,...,141.0,Mpfi,3.78,3.15,9.5,114.0,5400.0,16845.0,10.22,8.39
202,-1,95.0,Volvo,Gas,Turbo,Four,Sedan,Rwd,Front,109.1,...,141.0,Mpfi,3.78,3.15,8.7,160.0,5300.0,19045.0,12.37,9.40
203,-1,95.0,Volvo,Gas,Std,Four,Sedan,Rwd,Front,109.1,...,173.0,Mpfi,3.58,2.87,8.8,134.0,5500.0,21485.0,13.06,10.22
204,-1,95.0,Volvo,Diesel,Turbo,Four,Sedan,Rwd,Front,109.1,...,145.0,Idi,3.01,3.40,23.0,106.0,4800.0,22470.0,9.04,8.70

In [29]:
# Checking for dublicates
data.duplicated().sum()

0